### ISSUE TITLE
Sign-off from OEC legal on licensing and confidentiality acknowledgement

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#267]
Chris and Abby met with Mike Curley and Sarah Normandie (OEC legal) on 11/8. 

Notes & next steps:
- Confidentiality acknowledgement: Mike agrees we should only ask users to accept the confidentiality agreement once (e.g., during an on-boarding flow). He is going to look into tailoring the existing language to be more human friendly.
- OSS Licensing: Mike and Sarah are going to do further investigation, review Chris’ suggested language and put together a plan. (They seemed to be on board with the recommended direction.)
- We have a check-in scheduled for November 22.

**Comment by abbyraskin** [comment]
@cmgiven do you have any notes from your follow up meeting and can we close this one?

**Comment by cmgiven** [comment]
Yup.

Confidentiality agreement: We have slightly modified language that should be included as a footer item. We have agreement that this language does not have to be agreed to as part of the log in flow (and certainly not as part of every log in flow). Options are to show as part of the initial log in, to show as part of registration, or (most likely for the pilot) to show as part of an offline onboarding process.

A new item is that we should add a privacy policy, also a footer item. Once we have finalized the data collection requirements, we will share with Sarah so that she can draft such a policy. This also includes topics like data retention, which is being discussed OEC-wide.

OSS licensing: Mike asked for another couple of weeks to continue to research this one.

**Comment by cmgiven** [comment]
Find the revised language and a memo here: https://drive.google.com/drive/u/1/folders/1vPqrY5sSpD1FLZed1Snv3E6I66OlSGUN
