### ISSUE TITLE
From ChildrenController - validate that new orgId = existing orgId (may require DTO)

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/ecis-experimental#333]

**Comment by jlhogan** [comment]
Not sure that this is necessary due to: https://github.com/ctoec/ecis-experimental/blob/master/src/Hedwig/Validations/Attributes/OrgIdFromPathAttribute.cs and https://github.com/ctoec/ecis-experimental/blob/master/src/Hedwig/Validations/Attributes/SiteIdFromPathAttribute.cs which ensure that objects being created match the request path params

**Comment by mmazanec22** [comment]
Ok-- I think this is left over from some ancient history eng sync anyway.  I have no objections to closing it.
