### ISSUE TITLE
Should acronyms on reports page be spelled out?

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#387]
We're just using "CDC" in the table, without a legend like we have on the roster. See discussion here: https://github.com/ctoec/ecis-experimental/pull/385#discussion_r356147420

I'm not sure this is wrong. We can probably assume a user who accepts CDC funding knows what CDC is and doesn't need it defined. Still, an interesting accessibility/consistency question. Thus the issue title being a question. 

cc @mmazanec22 @atreni

**Comment by mmazanec22** [comment]
After reading a bit more, I'm starting to conclude that spelling out acronyms somewhere would be fine and we don't need to delve into associating the table and legend with ARIA (as I wondered in a later PR comment), since the tags are just text anyway.  Are reports always associated with a funding source?
