### ISSUE TITLE
http -> https redirect in staging/prod

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#401]
right now navigating to `http://stage.hedwig.ctoecskylight` serves you the site. should automatically redirect to https

**Comment by belucid** [comment]
Tracking this here: https://github.com/skylight-hq/ctoec-devops/issues/1

**Comment by speedcm** [comment]
In order to redirecting HTTP traffic (port 80) to HTTPS (port 443) for a Beanstalk environment with an application load balancer, the security configuration of the IIS webserver needs to be updated using the commands in the following link as per AWS:

- https://github.com/awsdocs/elastic-beanstalk-samples/blob/master/configuration-files/aws-provided/security-configuration/https-redirect/dotnet/https-redirect-load-balanced-dotnet.config 

This fix is to track the IIS webserver change only.  The DeveOps team will also need to switch the Beanstalk load balancer from classic to application via another issue.

**Comment by speedcm** [comment]
This issue is now done.
