### ISSUE TITLE
Edit state validation errors

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#427]
**Acceptance criteria:**
- [Implementation flexibility here - see Chris' comment below, added a couple bullets for general guidance/initial design thinking]
- If there is any missing information in a section that has been previously saved, show in-line alerts (see design below)
- If one of the sections in the step list has a validation error for a reason that blocks save (e.g., a new validation was added, or a required piece of information like first name was deleted) AND there is missing information, if a user selects save, only display the blocking errors in red

**Design:**
![image](https://user-images.githubusercontent.com/30734760/71025392-8f6e2900-20cc-11ea-82be-e84bcd08a4a4.png)

**Comment by abbyraskin** [comment]
@cmgiven could use your help figuring out how to break this out/articulate what's happening

**Comment by cmgiven** [comment]
I think this ticket will require some exploration and collaboration between engineering and design.

What is desired is to aggregate the missing information fields that are grouped, as shown.So instead of showing a separate error per field, i.e. one for certificate ID, one for town, and one for state, there is instead a single message, and the fields are highlighted. In addition to the Birth Certificate section, this also applies to Address in Family Info. 

This gets tricky if some of the fields are populated. For example, I might know that someone was born in Hartford, but not have their birth certificate in front of me to find the ID #. The ideal functionality is depicted in the comp: continuing to warn that the group of fields is missing information, but only highlighting the empty fields.

Alternatively, the fields could be warned about individually (this is mostly already built). However, the challenge we'll run into is that when the fields are on the same line, as shown with town and state, there is insufficient space for the message.

Perhaps the issue could simply be limited to those fields placed on the same line, in both cases, town and state, and the solution could be limited to solving for the two fields, one line problem.

There should be a lot of latitude here for a solution that balances design consistency and clarity, accessibility, and developer ergonomics.

Suggest this would be a great ticket for @mmazanec22 to take a crack at.
