### ISSUE TITLE
Add count to Care 4 Kids field on report

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#444]
As a provider, I want to see a count of Care 4 Kids recipients on my report to verify Care 4 Kid funding information was entered correctly before submitting my report.

**Acceptance Criteria:**
- Show a count of the total number of children enrolled for a given reporting period next to the Care 4 Kids field in the "Other revenue" portion of the report (see design below)

**Design:**
![image](https://user-images.githubusercontent.com/30734760/71186894-a1260c80-2243-11ea-92ea-8da62b5334ee.png)

**Comment by mmazanec22** [comment]
Per conversation with @jlhogan this raises some questions about how we're doing reports-- do we want to include kids with just C4K funding in CDC reports?  Is it misleading or meaningful to have a number on this page that represents only kids with both C4K and CDC funding?

**Comment by jlhogan** [comment]
Additionally: do we want to capture this count as a fixed number on the report itself, or just show it here to providers, and know that it can be calculated from the data ?

**Comment by cmgiven** [comment]
Sadly, this is a bit of a weird one. Although the general focus of the CDC report is the CDC kids, my understanding is this number is about the financial condition of the program in general, and is not specific to CDC kids. So we do need this count to include any kid who received a C4K subsidy during the reporting period, including those who did not also receive CDC funding.

The API currently just returns the CDC kids, so that would require some kind of change there, whether changing that endpoint or making a second call.

As for Julia's question about capturing the count, I think like the rest of the data shown on the report, I think we can continue to rely on the `AS OF` stuff to dynamically calculate it.
