### ISSUE TITLE
AWS - Hedwig - Support & Setup Test Environments – Dev (switch), QA, UAT

### ISSUE THREAD

**Issue by speedcm** [ctoec/ecis-experimental#88]
As a UAT Tester I need a controlled, stable environment to ensure the application meet expectations.

Setup and support the UAT test environment to support the hedwig project.  This requires:

a. Setting up new Beanstalk environment for UAT
b. Setting up new empty database (e.g. hedwig-uat) for UAT
b. Setting up new Azure DevOps Services Pipeline for UAT

Notes:
a. Procedures to perform UAT deployments must be authored and available in the wiki
b. Procedures to setup a new environment (e.g. UAT) must be authored and available in the wiki

**Comment by cmgiven** [comment]
I'm going to suggest we could scope this down. We don't have a QA team, and we don't expect to. We also don't have to maintain parallelism to any dependencies at the moment, and when we do, the one we know about (SASID Manager) only runs two environments (test and prod). So four environments seems like overkill to me.

Our current environment tracks the `master` branch. This is the behavior we'd expect for a dev or staging environment. (I prefer Staging to Dev, but that's just naming.)

We know we need a Production environment. This is the environment our users use. Deploys here are manually kicked off. In the future, deploys could run on a schedule, conditional on successful deployment in a lower environment.

I think there's a reasonable case for a middle environment. Something that's manually kicked off, but is populated with test data. It should be otherwise identical to prod. I'd call it Preprod, but UAT could also work. I'm not sure we need it now, but it seems like a fair future-looking step.

Do you see reason to have more than three environments, though?

**Comment by speedcm** [comment]
This issue has been updated for the creation of an UAT environment to serve as a stable, controlled testing environment.

**Comment by speedcm** [comment]
This issue is now complete.  The UAT environment has been setup and is accessible via:

- Beanstalk - http://hedwig-uat.us-east-2.elasticbeanstalk.com/
- RDS - hedwig.cvyhm8htm63c.us-east-2.rds.amazonaws.com (hedwig-uat)

Deployments to the UAT environment are manual.  To perform a manual deployment, perform these steps:

- https://github.com/ctoec/ecis-experimental/wiki/OPS:-Manual-Deployments

This issue was also used to rename the development environment to Staging.  The Staging environment is accessible via:

- Beanstalk - http://hedwig-staging.us-east-2.elasticbeanstalk.com/
- RDS - hedwig.cvyhm8htm63c.us-east-2.rds.amazonaws.com (hedwig-staging)
