### ISSUE TITLE
Query slow down

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#927]
Since `17d65452564290b5bd962b4992fc11f2dfd8ac18` response times for enrollment queries are much slower (> 4x)

This is due to the complexity of additional joins from https://github.com/ctoec/ecis-experimental/blob/master/src/Hedwig/Repositories/EnrollmentRepository.cs#L159

According to docs, multiple includes can greatly reduce query performance, and alternative patterns for loading data are required https://docs.microsoft.com/en-us/ef/core/querying/related-data#eager-loading

**Comment by cailyncodes** [comment]
*What happened?*
A member of the team noticed that the staging environment was taking approximately 20s to load the initial roster view. This was flagged to the full team in Slack and then two developers confirmed the issue both in staging and locally. A ticket (#927) was created and added to the current sprint project column. A developer picked up the ticket and began investigating.

*Why did it happen?*
The investigation revealed several unrelated issues. The primary cause of the slowdown was exceptionally large network responses, approximately 40MBs.

Issue 1:
The `TransformEntityFilterAttribute.UnsetTypeSubEntities` method does a depth-first recursive strategy to exclude child objects with a type in common with a parent object. When it encountered an array-like data type it would iterate over the array-like object and transform each entity. The check it used for array-like data was whether it was an `ICollection`. This matches `IList` and `ICollection` however it is a subtype of `IEnumerable`. The fundings array on `FundingSpace` was an `IEnumerable`. Therefore, this check failed and fundings were not removed from the `FundingSpace` object.

Issue 2:
After this was fixed (see below), additional investigation revealed that some site objects on an enrollment included additional enrollments. Through manually inspecting the database, it become apparent that only enrollments that had already exited (aka enrollments that would not show up on a roster and not be included with the date filtering) were included. In other words, only enrollments for children that had previous enrollments had this issue The issue was confirmed not be to with the `TransformEntityFilterAttritbute`. Instead, it was discovered to lie with one of the validations, specifically `FundingsAreValid`. `FundingsAreValid` retrieves all fundings for a given child. The model structure requires navigating through enrollment. With tracking on, this loaded those previous enrollments into the db context, which were then added to the response object.

*What is the solution?*
Issue 1:
Changing the check from `ICollection` to `IEnumerable`.

Issue 2:
Adding a AsNoTracking property to the `GetFundingsByChildId` repository method.

*How to prevent this in the future?*
To address the mystery added past enrollments, EntityFramework tracking needs to be closely considered when using repository queries. One option is to create no tracking versions of all queries and ensure that the no tracking versions are used in all post data retrieval steps.

To address the ICollection <> IEnumerable issue, the models could use the same type for all array-like data. Currently, there are ICollection, IList, and IEnumerable used.

Additionally, a meeting is scheduled for Thursday, April 9th to explore application performance monitoring. The attendees are Julia, Kyle, Paul, and Cailyn. This section will be updated pending that conversation.
